#!/bin/ruby

##############################################################
# THIS IS A LEGAL PROGRAM, DON'T USE THIS FOR ILLEGAL ATTACKS! 
# ONLY ASSHOLES ATTACK PRIVATE ORGS! 
# RESPECT!
# COPYRIGHT DIO-BRANDO, JOSH WASH 2021-2022
##############################################################

require_relative "lib/reqs"
require_relative "src/init"

arg_one = ARGV[0]
parse_one = ARGV[1]
arg_two = ARGV[2]
parse_two = ARGV[3]
if(arg_one == "--help" || arg_one == "-h")
    puts "Usage: dbuster [-h || --help] To show this message and exit
       dbuster [-u || --url] Url to attack"
exit(0)
end
if not arg_one
    puts "Invalid args!"
    puts "Usage: dbuster [-h || --help] To show this message and exit
       dbuster [-u || --url] Url to attack
       dbuster [-w || --wordlist] Custom wordlist to use"
    exit(0)
end
if(arg_one == "--version" || arg_one =="-v")
   puts "Copyright 2021-2022 DioBrando and Josh Wash.
This program are in 0.5v"
exit(0) 
end
if(arg_one == "--url" || arg_one == "-u")
    red = "\033[1;31m"
    green = "\033[1;32m"
    yellow = "\033[1;33m"
    cyan = "\033[1;36m"
    reset = "\033[0;0m"
    init_message()
    begin
        require_relative "lib/reqs"
    rescue LoadError
        error_initial()
    end
    url = parse_one
    
    line = File.readlines('wordlists/common.txt')
    for i in line
        if not url.end_with? '/' and not url.include? 'https:'
            new_url='https://'+url+'/'
            begin
                current_message(new_url);
                if(req(new_url,i.strip()) == 200)
                    puts(new_url+"#{green}"+i.strip()+"#{reset}")
                else
                end
            rescue Errno::ECONNREFUSED => e
                req(new_url,i.strip())
            end
        end
        if url.include? 'https:' and not url.end_with? '/'
            new_url=url+'/'
            begin
                current_message(new_url);
                if(req(new_url,i.strip()) == 200)
                    puts(new_url+"#{green}"+i.strip()+"#{reset}")
                else
                end
            rescue Errno::ECONNREFUSED => e
                req(new_url,i.strip())
            end
        end
        if not url.include? "/" and not url.include? "https:"
            new_url='https://'+url
            begin
                current_message(new_url);
                if(req(new_url,i.strip()) == 200)
                    puts(new_url+"#{green}"+i.strip()+"#{reset}")
                else
                end
            rescue Errno::ECONNREFUSED => e
                req(new_url,i.strip())
            end
        end
        begin
            req(url, i.strip())
            if(req(url, i.strip()) == 200)
                puts(url+"#{green}"+i.strip()+"#{reset}")
            end
        rescue SignalException => e
            puts "\n#{reset}[#{red}!#{reset}] Control+C detected!\nQuitting"    
            exit(0)
        rescue => e 
            req(url,i.strip())
        end
    end
end
